### ISSUE TITLE
GitHub action to check linting & formatting

### ISSUE THREAD

**Issue by falkben** [spacetelescope/DRESSCode#1]
- flake8
- black
- isort

add a readme section about this, and update dependencies

**Comment by falkben** [comment]
pre-commit hooks would be helpful, in addition/instead of github action https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

**Comment by mdecleir** [comment]
Do I understand correctly that the idea is to require that every contributed code has been run through flake8 and black before committing? I am familiar with black, not so much with flake8. Could you briefly explain me what the difference is?

**Comment by falkben** [comment]
yea, black is for formatting

flake8 does linting. it looks for errors in code. for example: undefined variables being used. https://flake8.pycqa.org/en/latest/

another similar tool to flake8 would be pylint, if you are familiar with that

**Comment by mdecleir** [comment]
Aha, I was not familiar with the term "linting". Thanks!

This would be a great addition to the repo!
