### ISSUE TITLE
Conform to style requirements in space telescope org

### ISSUE THREAD

**Issue by falkben** [spacetelescope/DRESSCode#23]
Conform to the style guide for space telescope located here: https://github.com/spacetelescope/style-guides/blob/master/guides/github-repositories.md

- [x] Convert Readme to Markdown for easier editing (for me at least)
- [x] Change copyright to "AURA"
- [x] Add code of conduct
- [x] Add maintainers (CODEOWNERS)
- [x] Add link back to original code: https://github.com/mdecleir/DRESSCode
- [x] Add links from readme to other documents

**Comment by mdecleir** [comment]
Because the PR (#24) that was going to close this issue was first merged into develop and then into main, this issue has not been closed automatically. This is the case for some other issues as well (e.g. #12, #15). It would be best to go through the issues and close the ones that are done.
