### ISSUE TITLE
Add requirements.txt file

### ISSUE THREAD

**Issue by falkben** [spacetelescope/DRESSCode#3]
`requirements.txt` file for our dependencies

currently:

- `astropy`
- `ccdproc`

**Comment by mdecleir** [comment]
Is that file only for python packages, or can it contain other things, such as the HEASoft software, WCS tools, etc.?

**Comment by falkben** [comment]
It would only include python package dependencies. For including HEASoft software, etc, creating a docker image containing the software would be the solution (they already have one, but I think we might need to customize it slightly) #11

**Comment by falkben** [comment]
We need to go back at some point and pin these dependencies, but for now closing.
