### ISSUE TITLE
comment pull requests with image of pipeline output

### ISSUE THREAD

**Issue by falkben** [spacetelescope/DRESSCode#41]
Comment pull requests with an image of the pipeline output.

Probably use this action to make the comment: https://github.com/marketplace/actions/comment-pull-request

We'll need a script that can take the fits output file and generate a JPEG/PNG, upload it to some image hosting service and make the comment a url in markdown:

`![image description](http://image-hosting.com/path/to/img.jpg)`

possible image hosting: [imgur](https://apidocs.imgur.com/)

This is because GitHub doesn't allow uploading images to issues/comments with their API.

**Comment by mdecleir** [comment]
One way to generate a jpeg/png from a fits file, is to plot it with astropy, and save the plot: see e.g. here: https://docs.astropy.org/en/stable/generated/examples/io/plot_fits-image.html
